### ISSUE TITLE
Request: Show only the highest priority

### ISSUE THREAD

**Issue by dat2** [gtdtxt/gtdtxt#6]
I'd like an option to show only my tasks above a certain priority threshold.

eg. `gtdtxt -p -gt[e] 8 work.gtd` would only show tasks that have a priority greater than 8. I haven't thought through the possible command line syntax but the idea is there 💯

**Comment by dashed** [comment]
There is now `--show-priority` option for one-sided range filter. 
Usage: 

`gtdtxt --show-priority='>= 8'`

`gtdtxt -y '>= 8'`
